#!/bin/sh
# Every lb config flag for Tekne (DEC-003). Run by live-build; never type flags by hand.
set -e

DEVUAN="http://deb.devuan.org/merged/"
# The Tokyo Night console palette and loglevel=3, as on installed systems
# (tekne-branding: /etc/default/grub.d/tekne-console.cfg, DEC-037).
CONSOLE="loglevel=3 vt.default_red=26,247,158,224,122,187,125,169,65,247,158,224,122,187,125,192 vt.default_grn=27,118,206,175,162,154,207,177,72,118,206,175,162,154,207,202 vt.default_blu=38,142,106,104,247,247,255,214,104,142,106,104,247,247,255,245"

lb config noauto \
	--mode debian \
	--architecture amd64 \
	--distribution excalibur \
	--parent-distribution excalibur \
	--archive-areas "main contrib non-free non-free-firmware" \
	--parent-archive-areas "main contrib non-free non-free-firmware" \
	--mirror-bootstrap "${DEVUAN}" \
	--mirror-chroot "${DEVUAN}" \
	--mirror-chroot-security "${DEVUAN}" \
	--mirror-binary "${DEVUAN}" \
	--mirror-binary-security "${DEVUAN}" \
	--parent-mirror-bootstrap "${DEVUAN}" \
	--parent-mirror-chroot "${DEVUAN}" \
	--parent-mirror-chroot-security "${DEVUAN}" \
	--parent-mirror-binary "${DEVUAN}" \
	--parent-mirror-binary-security "${DEVUAN}" \
	--keyring-packages devuan-keyring \
	--security true \
	--updates true \
	--initsystem sysvinit \
	--binary-images iso-hybrid \
	--bootloaders "grub-pc grub-efi" \
	--uefi-secure-boot disable \
	--bootappend-live "boot=live components quiet ${CONSOLE}" \
	--debian-installer none \
	--memtest none \
	--firmware-chroot false \
	--firmware-binary false \
	--cache true \
	--cache-packages true \
	--cache-indices false \
	--iso-application "tekne" \
	--iso-volume "Tekne ${TEKNE_VERSION:-dev}" \
	--iso-publisher "Tekne project" \
	--checksums sha256 \
	--source false \
	"${@}"
